name: Auto Version Bump

on:
  push:
    branches:
      - main    # or release branch if you prefer

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Extract current version
        id: get_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "current_version=$version" >> $GITHUB_ENV

      - name: Calculate next version
        id: bump_version
        run: |
          curr=${{ env.current_version }}
          base=${curr%-SNAPSHOT}
          IFS='.' read -r major minor patch <<< "$base"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch-SNAPSHOT"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "Bumping version: $curr -> $new_version"

      - name: Update pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ env.new_version }} -DgenerateBackupPoms=false

      - name: Commit and push new version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "Bump version to ${{ env.new_version }}"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
